name: "Test"

on: [push, pull_request]

jobs:
  build:
    name: Test build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target: ["ai.server"]
      fail-fast: false
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v4
      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN }}
      - name: Build
        uses: home-assistant/builder@master
        with:
          args: |
            --amd64 \
            --aarch64 \
            --no-latest \
            -i hassio-addon-${{ matrix.target }}-{arch} \
            --target ${{ matrix.target }} \
            --docker-hub ghcr.io/${{ github.actor }}
